apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: $CI_PROJECT_TITLE
  labels:
    team: app
spec:
  selector:
    matchLabels:
      app: $CI_PROJECT_TITLE
  endpoints:
  - port: web
    path: '/metrics'
