- name: Install Runner
  become: true
  apt:
    deb: https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb

- name: Create GitLab Runner SSL configuration folder.
  become: true
  file:
    path: /etc/gitlab-runner/certs
    state: directory
    owner: root
    group: root
    mode: 755

- name: Copy Certs for runner
  become: true
  copy:
    src: /etc/gitlab/ssl/{{ ansible_host }}.crt
    dest: /etc/gitlab-runner/certs/{{ ansible_host }}.crt
    remote_src: yes

- name: Install Service
  command: sudo gitlab-runner install --user root
  ignore_errors: yes

- name: Add Custom Registry to allowed
  become: true
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
          "insecure-registries" : [ "{{ ansible_host }}:5005" ]
      }

- name: Reload docker
  command: sudo service docker restart

- name: Register Runner
  shell: 'sudo gitlab-runner register \
  --non-interactive \
  --url "https://{{ ansible_host }}" \
  --registration-token "{{ registration_token }}" \
  --executor "docker" \
  --docker-image "docker:19.03.12" \
  --docker-tlsverify=false
  --description "docker-runner" \
  --docker-privileged \
  --tag-list "docker" \
  --run-untagged="true" \
  --locked="false" \ 
  --docker-volumes /var/run/docker.sock:/var/run/docker.sock
  --docker-cert-path /etc/gitlab/ssl/{{ ansible_host }}.crt'
